### ISSUE TITLE
Emoji shortcuts for Chrome OS

### ISSUE THREAD

**Issue by nathan-nz** [Arkshine/discourse-banner-featured-links#1]
Here is a link to how to do the emoji shortcuts in ChromeOS:

https://www.wikihow.com/Get-Emojis-on-Chromebook

Can that be incorporated as per the Windows and Mac ones? I can't find this in the code anywhere.

**Comment by Arkshine** [comment]
Do you mean the setting description here?

https://github.com/Arkshine/discourse-banner-featured-links/blob/8cca1a78f23d8cba2591715e89ed09900a590ac6/locales/en.yml#L16
